config/routes.rb
Rails.application.routes.draw do

  root 'menu#index'
  get 'menu/index'

  resources :projects do
    member do
    end

    collection do
      get 'role/:search_id' => 'projects#search_role'
      get 'place/:search_id' => 'projects#search_place'
      get 'skill/:search_id' => 'projects#search_skill'

      get 'role/:search_id/show/:id' => 'projects#role_show'
      get 'place/:search_id/show/:id' => 'projects#place_show'
      get 'skill/:search_id/show/:id' => 'projects#skill_show'
    end
  end

  get 'company' => 'menu#company'
  get 'privacy' => 'menu#privacy'
  get 'security' => 'menu#security'

  post 'applys/confirm'
  post 'applys/thanks'

  get 'contacts/index'
  post 'contacts/confirm'
  post 'contacts/thanks'

end

app/models/apply.rb
class Apply
  include ActiveModel::Model
  require 'carrierwave/orm/activerecord'
  #mount_uploader :avatar, AvatarUploader
  attr_accessor :name, :email, :birthdate, :sex, :message, :project_id, :avatar, :file_path

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/business.rb
class Business < ActiveRecord::Base
end

app/models/contact.rb
class Contact
  include ActiveModel::Model
  #mount_uploader :avatar, AvatarUploader
  attr_accessor :name, :enterprise, :post, :email, :tell, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :enterprise, :presence => {:message => '会社名を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
  validates :tell, :presence => {:message => '電話番号を入力してください'}
  validates :message, :presence => {:message => 'メッセージを入力してください'}
end

app/models/environment.rb
class Environment < ActiveRecord::Base
  belongs_to :project
  belongs_to :skill
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
  self.inheritance_column = :_type_disabled
  has_many :environments
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :environments
end

app/models/store.rb
class Store < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader

  validates :avatar, :presence => {message: '経歴書を添付してください'}
end

app/models/type.rb
class Type < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/applys_controller.rb
class ApplysController < ApplicationController
  def confirm
    @apply = Apply.new(apply_params)
    @store = Store.new(store_params)
    @project = Project.find(@apply.project)

    search = search_params  
    @search_id = search[:id]
    @search_name = search[:name]
    @link = search[:link]

    if @apply.valid? && @store.valid?
      @apply.avatar = @apply.avatar.original_filename
      @apply.file_path = @store.avatar.current_path
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => "../projects/show"
    end
  end

  def thanks
    # メール送信
   @apply = Apply.new(apply_params)
   ApplyMailer.received_email(@apply).deliver
   ApplyMailer.sended_email(@apply).deliver
   # 完了画面を表示
   render :action => 'thanks'
  end
end

private

 def apply_params
   params.require(:apply).permit(:name, :email, :birthdate, :sex, :project, :avatar, :file_path)
 end

 def store_params
   params.require(:apply).permit(:avatar)
 end

 def search_params
   params.require(:search).permit(:id, :name, :link)
 end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contact = Contact.new
  end

  def confirm
    @contact = Contact.new(contact_params)

    if @contact.valid?
      render :action => 'confirm'
    else
      render :action => 'index'
    end

  end

  def thanks
    @contact = Contact.new(contact_params)
    ContactMailer.sended_email(@contact).deliver
    render :action => 'thanks'
  end

  private

   def contact_params
     params.require(:contact).permit(:name, :enterprise, :post, :email, :tell, :message)
   end

end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
    @roles = Role.all
    @skills = Skill.all
    @places = Place.all
  end

  def company
  end

  def privacy
  end

  def security
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController  
  helper_method :sort_column, :sort_direction
  def index    
    @projects = Project.order("updated_at DESC")
  end

  def search_role
    @projects = Project.where(role: params[:search_id]).order(sort_column + ' ' + sort_direction)
    @search = Role.find(params[:search_id])
    @link = 'role'
    render :action => "index"
  end

  def search_place
    @projects = Project.where(place: params[:search_id]).order(sort_column + ' ' + sort_direction)
    @search = Place.find(params[:search_id])
    @link = 'place'
    render :action => "index"
  end

  def search_skill
    environments = Environment.where(skill: params[:search_id]).select("project_id").group("project_id")
    skills = Array.new
    environments.each do |environment|
      skills << environment.project
    end

    @projects = Project.where(id: skills).order(sort_column + ' ' + sort_direction)
    @search = Skill.find(params[:search_id])
    @link = 'skill'
    render :action => "index"
  end

  def role_show
    @role = Role.find(params[:search_id])
    @search_name = @role.name
    @link = 'role'

    show
  end

  def place_show
    @place = Place.find(params[:search_id])
    @search_name = @place.name
    @link = 'place'

    show
  end

  def skill_show
    @skill = Skill.find(params[:search_id])
    @search_name = @skill.name
    @link = 'skill'

    show
  end

  private

    def show
      @project = Project.find(params[:id])
      @search_id = params[:search_id]

      @apply = Apply.new
      @apply.project_id = @project.id
      @store = Store.new
      @apply.avatar = Store.new

      render :action => 'show'
    end
    
  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "desc"
  end
 
  def sort_column
    Project.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
    end
end

app/helpers/applys_helper.rb
module ApplysHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/applys/confirm.html.erb
<br/>
<div class="row valign-wrapper orange lighten-5">
  <div class="col s12 valign-wrapper navi-root">
    <%= link_to "HOME", "/" %>
    <i class="material-icons">chevron_right</i>
    <%= link_to @search_name, "/projects/" + @link + "/" + @search_id.to_s %>
    <i class="material-icons">chevron_right</i>
    <%= link_to @project.title, "/projects/" + @link + "/" + @search_id.to_s + "/show/" + @project.id.to_s %>
  </div>
</div>

<div class="container">

  <h5>この内容で間違いありませんか？</h5>

  <%= render 'projects/detail' %>

  <div class="card-panel white">
  <%= form_for @apply, :url => applys_thanks_path do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :birthdate %>
  <%= f.hidden_field :sex %>
  <%= f.hidden_field :project_id %>
  <%= f.hidden_field :avatar %>
  <%= f.hidden_field :file_path %>
  <div class="row">
    <div class="col l2 m3 s12 grey-text"><b>名前</b></div>
    <div class="col l10 m9 s12"><%= @apply.name %></div>
  </div>
  <div class="row">
    <div class="col l2 m3 s12 grey-text"><b>Email</b></div>
    <div class="col l10 m9 s12"><%= @apply.email %></div>
  </div>
  <div class="row">
    <div class="col l2 m3 s12 grey-text"><b>生年月日</b></div>
    <div class="col l10 m9 s12"><%= @apply.birthdate %></div>
  </div>
  <div class="row">
    <div class="col l2 m3 s12 grey-text"><b>性別</b></div>
    <div class="col l10 m9 s12">
      <% if @apply.sex.to_i == 1 then %>男性<% else %>女性<% end %>
    </div>
  </div>
  <div class="row">
    <div class="col l2 m3 s12 grey-text"><b>経歴書</b></div>
    <div class="col l10 m9 s12"><%= @apply.avatar %></div>
  </div>
  <hr/>
  <%= f.submit "エントリー", :class => "btn" %>
  <% end %>
  </div>

</div>

app/views/applys/thanks.html.erb
<div class="container">
  <div class="col s12 card-panel">
    <h4>ご応募ありがとうございます</h4>
    <br/>
    <br/>
    <p>入力されたメールアドレス宛に、確認のメールを送信しました。</p>
    <p>メールが届かない場合はメールアドレスの入力が正しくなかった可能性がありますので、再度お問い合わせください。</p>
  </div>
</div>

app/views/contacts/confirm.html.erb
<div class="container">

  <div class="col s12 card-panel confirm-form">
    <h4 class="grey-text">この内容で送信しますか？</h4>
    <%= form_for @contact, :url => contacts_thanks_path do |f| %>
    <%= f.hidden_field :name %>
    <%= f.hidden_field :enterprise %>
    <%= f.hidden_field :post %>
    <%= f.hidden_field :email %>
    <%= f.hidden_field :tell %>
    <%= f.hidden_field :message %>
    <div class="row">
      <div class="col l3 m4 s6">名前</div>
      <div class="col l9 m8 s12"><%= @contact.name %></div>
    </div>
    <div class="row">
      <div class="col l3 m4 s6">会社名</div>
      <div class="col l9 m8 s12"><%= @contact.enterprise %></div>
    </div>
    <div class="row">
      <div class="col l3 m4 s6">所属・役職</div>
      <div class="col l9 m8 s12"><%= @contact.post %></div>
    </div>
    <div class="row">
      <div class="col l3 m4 s6">Email</div>
      <div class="col l9 m8 s12"><%= @contact.email %></div>
    </div>
    <div class="row">
      <div class="col l3 m4 s6">Tell</div>
      <div class="col l9 m8 s12"><%= @contact.tell %></div>
    </div>
    <div class="row">
      <div class="col l3 m4 s6">問い合わせ内容</div>
      <div class="col l9 m8 s12"><%= @contact.message %></div>
    </div>
    <br/>
    <%= f.submit "送信", :class => "btn" %>
    <% end %>
    </div>
  </div>
</div>

app/views/contacts/index.html.erb
<div class="container">

  <% if @contact.errors.any? %>
    <div class="card-panel red lighten-4 red-text text-accent-4">
      <h5>入力内容にエラーがあります</h5>
      <ul>
        <% @contact.errors.each do |attr, msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col s12 card-panel">
    <h4 class="grey-text">Contact お問い合わせ</h4>
    <div class="container">
      <%= form_for @contact, :url => contacts_confirm_path do |f| %>
        <div>
          <%= f.label "名前", :class => "" %>
          <%= f.text_field :name, :class => "" %>
        </div>

        <div>
          <%= f.label "会社名" %>
          <%= f.text_field :enterprise, :class => "" %>
        </div>

        <div>
          <%= f.label "所属・役職" %>
          <%= f.text_field :post, :class => "" %>
        </div>

        <div>
          <%= f.label :email, :class => "" %>
          <%= f.email_field :email, :class => "" %>
        </div>

        <div>
          <%= f.label :tell %>
          <%= f.number_field :tell, :class => "" %>
        </div>

        <div>
          <%= f.label "問い合わせ内容" %><br>
          <%= f.text_area :message, :class => "materialize-textarea" %>
        </div>

        <div>&nbsp;</div>
        <div>
          <%= f.submit "送信", :class => "btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/contacts/thanks.html.erb
<div class="container">

  <div class="col s12 card-panel">
    <h4>お問い合わせを承りました。</h4>
    <br/>
    <br/>
    <br/>
    <br/>
    <p class="right-align">株式会社 Blue Star</p>
  </div>

</div>

app/views/layouts/application.html のコピー.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title><%= content_for?(:title) ? yield(:title) : "Providejobs" %></title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'applications_internet.png' %>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js"></script>
  </head>
  <body class="blue-grey-text text-darken-4" style="background-color: #008aa8;">
  <nav>
    <div class="nav-wrapper orange lighten-2">
      <%= link_to("/") do %><%= image_tag "tryjob_logo_white.png", :width => "220px" %><% end %>
    </div>
  </nav>

    <%= yield %>

  <footer class="page-footer orange lighten-2">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <p class="">
          </p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class=""></h5>
          <ul>
            <li class="valign-wrapper"><i class="material-icons">stop</i><%= link_to "運営会社", "http://www.bluestar.jpn.com/" %></li>
            <li class="valign-wrapper"><i class="material-icons">stop</i><%= link_to "お問い合わせ", contact_path %></li>
            <li class="valign-wrapper"><i class="material-icons">stop</i><%= link_to "セキュリティポリシー", security_path %></li>
            <li class="valign-wrapper"><i class="material-icons">stop</i><%= link_to "プライバシーポリシー", privacy_path %></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container blue-grey-text text-darken-4">
      Copyright © 2016 BlueStar Inc. All Rights Reserved.
      <%= link_to "", "", :class => "right" %>
      </div>
    </div>
  </footer>

  <%= javascript_include_tag "application" %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
  <script>
  $(document).ready(function(){
    $('.parallax').parallax();
  });


  /*$(document).ready(function(){
    var url = window.location.href ;
    if(url.match(/menu/i)){
      $('html,body').animate({ scrollTop: 500 }, 10);
    }
    return false;
  });*/
  </script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title><%= content_for?(:title) ? yield(:title) : "Providejobs" %></title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'applications_internet.png' %>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js"></script>
  </head>
  <body class="blue-grey-text text-darken-4 orange lighten-5">
  <nav>
    <div class="nav-wrapper orange lighten-2">
      <%= link_to("/") do %><%= image_tag "tryjob_logo.png", :height => "100%", :class => "logo" %><% end %>
    </div>
  </nav>

    <%= yield %>

  <footer class="page-footer orange lighten-2">
    <div class="row">
      <div class="col l2 m3 s12 center">
        <%= link_to("/") do %><%= image_tag "tryjob_logo.png", :height => "50px" %><% end %>
      </div>
      <div class="col l10 m9 s12">
        <div class="col l12 m12 s12">
          <div class="col l3 m6 s12"><%= link_to "運営会社", company_path %></div>
          <div class="col l3 m6 s12"><%= link_to "お問い合わせ", contacts_index_path %></div>
          <div class="col l3 m6 s12"><%= link_to "セキュリティポリシー", security_path %></div>
          <div class="col l3 m6 s12"><%= link_to "プライバシーポリシー", privacy_path %></div>
        </div>
        <div class="col l12 m12 s12 blue-grey-text text-darken-4">
          Copyright © 2016 BlueStar Inc. All Rights Reserved.
        </div>
      </div>
    </div>
  </footer>

  <%= javascript_include_tag "application" %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
  <script>
  $(document).ready(function(){
    $('.parallax').parallax();
  });

  $('.datepicker').ready(function() {
    /* デートピッカー */
    var $input = $('.datepicker').pickadate({
      format: 'yyyy/mm/dd',
      selectMonths: true, // Creates a dropdown to control month
      selectYears: 30, // Creates a dropdown of 15 years to control year
      monthsFull: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月']
    });
    // Use the picker object directly.
    var picker = $input.pickadate('picker')
    picker.set('select', [1985, 1, 1]);
  });
  </script>
  </body>
</html>

app/views/menu/company.html.erb
<div class="container">
  <div class="col s12 card-panel">
    <h4 class="grey-text">会社概要</h4>
    <table class="bordered">
      <thead><tr>
        <th>会社名</th>
        <th>株式会社 Blue Star</th>
      </tr></thead>
      <tbody><tr>
        <td>業務内容</td>
        <td>
          ITコンサルティング<br/>
          システムインテグレーション
        </td>
      </tr><tr>
        <td>代表者</td>
        <td>黒木 聡</td>
      </tr><tr>
        <td>所在地</td>
        <td>〒141-0021 東京都品川区上大崎2-15-19</td>
      </tr><tr>
        <td>主要取引先</td>
        <td>
          楽天株式会社<br/>
          EMCジャパン株式会社<br/>
          TISビジネスコンサルタンツ株式会社<br/>
          デロイト トーマツ コンサルティング合同会社<br/>
          株式会社リクルートホールディングス<br/>
          株式会社リクルートマーケティングパートナーズ<br/>
          株式会社リクルートテクノロジーズ<br/>
          株式会社ベイカレントコンサルティング<br/>
          他（敬称略・順不同）
          </td>
      </tr></tbldy>
    </table>
  </div>
</div>

app/views/menu/privacy.html.erb
<div class="container">
  <div class="col s12 card-panel">
    <h4 class="grey-text">Privacy Policy 個人情報保護方針</h4>
    <p>１．個人情報保護宣言<br/>
    株式会社Blue Star（以下「弊社」といいます。）は、皆様へ安心・安全・信頼のサービスを提供するに当り、皆様の全ての個人に関する情報(以下「個人情報」といいます。)の取り扱いについて規定を定め、個人情報の適切な保護に努めてまいります。</p>
    <p>２．個人情報保護方針<br/>
    （１）弊社は、個人情報保護法及び通信の秘密に係る電気通信事業法の規定その他の関係法令を遵守します。<br/>
    （２）弊社は、電気通信事業における個人情報保護に関するガイドライン（平成16年8月31日総務省告示第695号）を遵守します。<br/>
    （３）弊社では取り扱うすべての個人情報に対し、適切な管理を行います。<br/>
    （４）弊社で業務に従事するすべての者は、会員皆様をはじめとする各種個人情報を守り、その信頼に応えます。<br/>
    （５）弊社は、情報への不正アクセス、情報の紛失、破壊、改ざん及び漏えいなどを防ぐため、必要かつ適切な安全管理措置を講じるとともにその改善に努めます。</p>
    <p>３．個人情報の取扱について<br/>
    （１）利用目的の特定<br/>
    弊社では、取得した皆様の氏名、住所、電話番号等の個人情報を下記の目的で利用します。
    弊社のサービスの提供、本人確認、料金の請求、お問合せ対応、弊社のサービス等の変更・休廃止の通知、弊社が提供する他サービスのお知らせ・各種イベント・キャンペーンの案内に利用いたします。<br/>
    （２）個人情報の開示<br/>
    弊社は、皆様から自己に関する個人情報の開示の請求があった場合は、本人確認を行ったうえで、これに応じます。<br/>
    また、個人情報の内容の訂正等の申出があった場合も、速やかに対応いたします。<br/>
    （３）個人情報の利用・提供<br/>
    サービスを提供するために必要な範囲でお客さまの個人情報を取得し、取得目的の範囲内で利用・提供を行います。<br/>
    （４）第三者提供<br/>
    弊社は、個人情報を取得目的の範囲内で利用するとともに、適切な方法で管理し、個人情報の提供先とその利用目的を通知し承諾を得ることを行わない限り、第三者に個人情報を開示、提供しないものとします。
    ただし、次の場合はこの限りではありません。弊社が行う個人情報の第三者提供は以下の通りです。<br/>
    ・刑事訴訟法第２１８条（令状による差押え・捜索・検証）その他同法の定めに基づく強制の処分が行なわれた場合。<br/>
    ・特定電気通信役務提供者の損害賠償責任の制限及び発信者情報の開示に関する法律第４条（発信者情報の開示請求等）に基づく開示請求の要件が充足された場合。<br/>
    ・生命、身体又は財産の保護のために必要があると弊社が判断した場合。</p>
    <p>４．個人情報のお問い合わせ
    弊社保有の個人情報の取り扱いに関するお問い合わせは、以下までお願いします。</p>
  </div>
</div>

app/views/menu/security.html.erb
<div class="container">
  <div class="col s12 card-panel">
    <h4 class="grey-text">Security Policy 情報セキュリティ方針</h4>

    <p>株式会社Blue Star（以下「当社」）は、当社における情報資産をあらゆる脅威から守るとともに、社会からの信頼に応える為、次のとおり情報セキュリティ基本方針を策定し、遵守することを宣言します。</p>

  <p>・情報セキュリティに関する法令、国が定める指針、別途定める関係各規定・契約等の規範を遵守します。<br/>
  ・情報セキュリティに関する責任を明確にし、対策を実施するための組織体制を整備します。<br/>
  ・情報資産の適正な管理、運用を推進するため、情報セキュリティリスクを識別し、リスクアセスメントを実施するとともに、必要に応じて組織的、物理的、人的、技術的な対策を実施します。また、情報セキュリティに関する問題が発生した場合には迅速に対応し、その被害を最小限に留めます。<br/>
  ・全従業員へこの基本方針に基づいた情報セキュリティに関する定期的な教育、啓発を実施し、周知徹底を行います。<br/>
  ・個人情報については、当社の「個人情報保護方針（プライバシーポリシー）」に基づいて管理します。<br/>
  ・上記項目を含む情報セキュリティマネジメントシステムについて定期的な見直しを実施し、継続的な改善を行います。</p>
  </div>
</div>

app/views/projects/index.html.erb
<br/>
<div class="row orange lighten-5">
  <div class="col s12 valign-wrapper navi-root">
    <%= link_to "HOME", menu_index_path %>
    <i class="material-icons">chevron_right</i>
    <%= link_to @search.name, "/projects/" + @link + "/" + @search.id.to_s %>
  </div>
</div>
<br/>
<!-- 以下テーブルで出力するように修正 -->
<div class="container">
<div class="row">
<table class="sort">
	<thead>
		<tr class="orange lighten-3">
			<td>詳細</td>
			<td><%= sortable "title", "案件名" %></td>
			<td><%= sortable "role", "役職" %></td>
			<td><%= sortable "fee", "報酬" %></td>
			<td><%= sortable "place", "勤務地" %></td>
			<td><%= sortable "skill", "技術" %></td>
		</tr>
	</thead>
	<% @projects.each do |project| %>
	<tbody>
		<tr>
			<th><%= link_to "詳細", "/projects/" + @link + "/" + @search.id.to_s + "/show/" + project.id.to_s, :style=>"color:blue;" %></th>
			<th><%= project.title %></th>
			<th>
				<%= Role.find(project.role).name %>
			</th>
			<th>
				〜 <%= project.fee %>万/月
			</th>
			<th>
			<%= Place.find(project.place).name %>
			</th>
			<th>
				<% environments = Environment.where(project: project.id) %>
              	<% environments.each do |environment| %>
                	<% if !Skill.find_by_id(environment.skill).blank? then %>
                  	<%= Skill.find(environment.skill).name %>&nbsp;
                	<% end %>
              	<% end %>
            </th>
		</tr>
	</tbody>
	<% end %>
</table>
</div>
</div>

app/views/projects/show.html.erb
<br/>
<div class="row valign-wrapper orange lighten-5">
  <div class="col s12 valign-wrapper navi-root">
    <%= link_to "HOME", "/" %>
    <i class="material-icons">chevron_right</i>
    <%= link_to @search_name, "/projects/" + @link + "/" + @search_id.to_s %>
    <i class="material-icons">chevron_right</i>
    <%= link_to @project.title, "/projects/" + @link + "/" + @search_id.to_s + "/show/" + @project.id.to_s %>
  </div>
</div>

<div class="container">

<br/><br/>
  <%= render 'projects/detail' %>
<br/><br/>

  <% if @apply.errors.any? || @store.errors.any? %>
    <div class="card-panel red lighten-4 red-text text-accent-4">
      <h5>入力内容にエラーがあります</h5>
      <ul>
        <% @apply.errors.each do |attr, msg| %>
          <li><%= msg %></li>
        <% end %>
        <% @store.errors.each do |attr, msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <div class="card-panel white">
      <%= form_for @apply, :url => applys_confirm_path do |f| %>
        <%= f.hidden_field :project_id %>
        <%= hidden_field_tag 'search[id]', @search_id %>
        <%= hidden_field_tag 'search[name]', @search_name %>
        <%= hidden_field_tag 'search[link]', @link %>
        <h5 class="orange-text">この案件に応募しますか？</h5>

        <div>
          <%= f.label "名前" %>
          <%= f.text_field :name %>
        </div>

        <div>
          <%= f.label :email %>
          <%= f.email_field :email %>
        </div>

        <div>
          <%= f.label "生年月日" %>
          <%= f.date_field :birthdate, :class => "datepicker" %>
        </div>

        <div>
          <%= f.label "性別" %><br>
          <%= f.radio_button :sex, 1 %> <%= f.label :sex_1, "男性" %><br/>
          <%= f.radio_button :sex, 2 %> <%= f.label :sex_2, "女性" %>
        </div>

        <div class="file-field input-field">
          <div class="btn">
            <span>経歴書</span>
            <%= f.file_field :avatar %>
          </div>
          <div class="file-path-wrapper">
            <input class="file-path validate" type="text">
          </div>
        </div>

        <div>&nbsp;</div>
        <div>
          <%= f.submit "エントリー", :class => "btn" %>
        </div>
      <% end %>
    </div>

<%= link_to @search_name + "カテゴリーに戻る", "/projects/" + @link + "/" + @search_id.to_s, :class => "btn" %>

</div>